/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dnebinger.subsystem.events.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EventAttendee service. Represents a row in the &quot;SUBSYS_EventAttendee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.dnebinger.subsystem.events.model.impl.EventAttendeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.dnebinger.subsystem.events.model.impl.EventAttendeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventAttendee
 * @see com.dnebinger.subsystem.events.model.impl.EventAttendeeImpl
 * @see com.dnebinger.subsystem.events.model.impl.EventAttendeeModelImpl
 * @generated
 */
@ProviderType
public interface EventAttendeeModel extends BaseModel<EventAttendee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a event attendee model instance should use the {@link EventAttendee} interface instead.
	 */

	/**
	 * Returns the primary key of this event attendee.
	 *
	 * @return the primary key of this event attendee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this event attendee.
	 *
	 * @param primaryKey the primary key of this event attendee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the surrogate ID of this event attendee.
	 *
	 * @return the surrogate ID of this event attendee
	 */
	public long getSurrogateId();

	/**
	 * Sets the surrogate ID of this event attendee.
	 *
	 * @param surrogateId the surrogate ID of this event attendee
	 */
	public void setSurrogateId(long surrogateId);

	/**
	 * Returns the event ID of this event attendee.
	 *
	 * @return the event ID of this event attendee
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this event attendee.
	 *
	 * @param eventId the event ID of this event attendee
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the user ID of this event attendee.
	 *
	 * @return the user ID of this event attendee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this event attendee.
	 *
	 * @param userId the user ID of this event attendee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this event attendee.
	 *
	 * @return the user uuid of this event attendee
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this event attendee.
	 *
	 * @param userUuid the user uuid of this event attendee
	 */
	public void setUserUuid(String userUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EventAttendee eventAttendee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EventAttendee> toCacheModel();

	@Override
	public EventAttendee toEscapedModel();

	@Override
	public EventAttendee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}