/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dnebinger.subsystem.events.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.dnebinger.subsystem.events.model.EventAttendee;
import com.dnebinger.subsystem.events.model.EventAttendeeModel;
import com.dnebinger.subsystem.events.model.EventAttendeeSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the EventAttendee service. Represents a row in the &quot;SUBSYS_EventAttendee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EventAttendeeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EventAttendeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EventAttendeeImpl
 * @see EventAttendee
 * @see EventAttendeeModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EventAttendeeModelImpl extends BaseModelImpl<EventAttendee>
	implements EventAttendeeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a event attendee model instance should use the {@link EventAttendee} interface instead.
	 */
	public static final String TABLE_NAME = "SUBSYS_EventAttendee";
	public static final Object[][] TABLE_COLUMNS = {
			{ "surrogateId", Types.BIGINT },
			{ "eventId", Types.BIGINT },
			{ "userId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("surrogateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("eventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table SUBSYS_EventAttendee (surrogateId LONG not null primary key,eventId LONG,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table SUBSYS_EventAttendee";
	public static final String ORDER_BY_JPQL = " ORDER BY eventAttendee.surrogateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SUBSYS_EventAttendee.surrogateId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.dnebinger.subsystem.events.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.dnebinger.subsystem.events.model.EventAttendee"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.dnebinger.subsystem.events.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.dnebinger.subsystem.events.model.EventAttendee"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.dnebinger.subsystem.events.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.dnebinger.subsystem.events.model.EventAttendee"),
			true);
	public static final long EVENTID_COLUMN_BITMASK = 1L;
	public static final long SURROGATEID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static EventAttendee toModel(EventAttendeeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		EventAttendee model = new EventAttendeeImpl();

		model.setSurrogateId(soapModel.getSurrogateId());
		model.setEventId(soapModel.getEventId());
		model.setUserId(soapModel.getUserId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<EventAttendee> toModels(EventAttendeeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<EventAttendee> models = new ArrayList<EventAttendee>(soapModels.length);

		for (EventAttendeeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.dnebinger.subsystem.events.service.util.ServiceProps.get(
				"lock.expiration.time.com.dnebinger.subsystem.events.model.EventAttendee"));

	public EventAttendeeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _surrogateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSurrogateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _surrogateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EventAttendee.class;
	}

	@Override
	public String getModelClassName() {
		return EventAttendee.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("surrogateId", getSurrogateId());
		attributes.put("eventId", getEventId());
		attributes.put("userId", getUserId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long surrogateId = (Long)attributes.get("surrogateId");

		if (surrogateId != null) {
			setSurrogateId(surrogateId);
		}

		Long eventId = (Long)attributes.get("eventId");

		if (eventId != null) {
			setEventId(eventId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}
	}

	@JSON
	@Override
	public long getSurrogateId() {
		return _surrogateId;
	}

	@Override
	public void setSurrogateId(long surrogateId) {
		_surrogateId = surrogateId;
	}

	@JSON
	@Override
	public long getEventId() {
		return _eventId;
	}

	@Override
	public void setEventId(long eventId) {
		_columnBitmask |= EVENTID_COLUMN_BITMASK;

		if (!_setOriginalEventId) {
			_setOriginalEventId = true;

			_originalEventId = _eventId;
		}

		_eventId = eventId;
	}

	public long getOriginalEventId() {
		return _originalEventId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			EventAttendee.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EventAttendee toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EventAttendee)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EventAttendeeImpl eventAttendeeImpl = new EventAttendeeImpl();

		eventAttendeeImpl.setSurrogateId(getSurrogateId());
		eventAttendeeImpl.setEventId(getEventId());
		eventAttendeeImpl.setUserId(getUserId());

		eventAttendeeImpl.resetOriginalValues();

		return eventAttendeeImpl;
	}

	@Override
	public int compareTo(EventAttendee eventAttendee) {
		long primaryKey = eventAttendee.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EventAttendee)) {
			return false;
		}

		EventAttendee eventAttendee = (EventAttendee)obj;

		long primaryKey = eventAttendee.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EventAttendeeModelImpl eventAttendeeModelImpl = this;

		eventAttendeeModelImpl._originalEventId = eventAttendeeModelImpl._eventId;

		eventAttendeeModelImpl._setOriginalEventId = false;

		eventAttendeeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EventAttendee> toCacheModel() {
		EventAttendeeCacheModel eventAttendeeCacheModel = new EventAttendeeCacheModel();

		eventAttendeeCacheModel.surrogateId = getSurrogateId();

		eventAttendeeCacheModel.eventId = getEventId();

		eventAttendeeCacheModel.userId = getUserId();

		return eventAttendeeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{surrogateId=");
		sb.append(getSurrogateId());
		sb.append(", eventId=");
		sb.append(getEventId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.dnebinger.subsystem.events.model.EventAttendee");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>surrogateId</column-name><column-value><![CDATA[");
		sb.append(getSurrogateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>eventId</column-name><column-value><![CDATA[");
		sb.append(getEventId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = EventAttendee.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			EventAttendee.class
		};
	private long _surrogateId;
	private long _eventId;
	private long _originalEventId;
	private boolean _setOriginalEventId;
	private long _userId;
	private long _columnBitmask;
	private EventAttendee _escapedModel;
}